on: pull_request
name: PR
jobs:
  PR_flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm i
      run: |
        npm install
    - name: lint
      run: |
        npm run lint
    - name: test
      run: |
        npm run test
    - name: build
      run: |
        npm run build
